from __future__ import annotations


STRATEGY_NAME = "vwap_zscore_fade"
INSTRUMENT = "NQ"
TIMEFRAME = "5min"

SOURCE_TIMEZONE = "UTC"
STRATEGY_TIMEZONE = "America/New_York"
SESSION_OPEN = "09:30"

BAR_INTERVAL_MINUTES = 5
RTH_START_SESSION_MINUTE = 0
NO_ENTRY_BEFORE_SESSION_MINUTE = 60
NO_ENTRY_AT_OR_AFTER_SESSION_MINUTE = 360
LAST_RTH_BAR_OPEN_SESSION_MINUTE = 385
SESSION_FORCE_FLAT_MINUTE = 390

ENTRY_Z_THRESHOLD = 2.0
Z_WINDOW = 20
SIGNAL_MIN_BARS = 20
VOLUME_Z_WINDOW = 20

ATR_WINDOW = 14
STOP_ATR_MULTIPLE = 1.5
MAX_BARS_HELD = 12

SLIPPAGE_TICKS_PER_SIDE = 1
NQ_TICK_SIZE = 0.25
NQ_POINT_VALUE = 20.0
NQ_TICK_VALUE = 5.0
